apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-db-deployment-w10t2
  labels:
    app: customer-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-db
  template:
    metadata:
      labels:
        app: customer-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config-w10t2
                  key: CUSTOMERS_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret-w10t2
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret-w10t2
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: customer-db-service-w10t2
  labels:
    app: customer-db
spec:
  selector:
    app: customer-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
